---
name: rtlamr2mqtt
version: 2.3.3
slug: rtlamr2mqtt
panel_icon: mdi:gauge
description: RTLAMR to MQTT Bridge
startup: application
boot: auto
map:
  - config:rw
url: https://github.com/davidflypei/rtlamr2mqtt2
uart: true
udev: true
usb: true
host_network: false
hassio_api: true
arch:
  - amd64
  - i386
  - armv7
  - armhf
  - aarch64
services:
  - mqtt:need
options:
  general:
    sleep_for: 0
    verbosity: debug
    listen_only: false
    tickle_rtl_tcp: false
    device_id: single
  mqtt:
    ha_autodiscovery: true
    ha_autodiscovery_topic: homeassistant
    base_topic: rtlamr
    tls_enabled: false
  custom_parameters:
    rtltcp: "-s 2048000"
    rtlamr: "-unique=true"
  meters:
    - id: 123456789
      protocol: scm+
      name: gas_meter
      format: "####.###"
      unit_of_measurement: m³
      icon: mdi:gas_canister
      device_class: gas
schema:
  general:
    sleep_for: int
    verbosity: list(debug|normal)?
    listen_only: bool?
    tickle_rtl_tcp: bool?
    device_id: match((^single|^(0[xX])?[A-Fa-f0-9]+:(0[xX])?[A-Fa-f0-9]+$))
  mqtt:
    host: str?
    port: int?
    user: str?
    password: str?
    ha_autodiscovery: bool?
    ha_autodiscovery_topic: str?
    base_topic: str
    tls_enabled: bool?
    tls_ca: str?
    tls_cert: str?
    tls_keyfile: str?
    tls_insecure: bool?
  custom_parameters:
    rtltcp: str?
    rtlamr: str?
  meters:
    - id: 1552818688
      protocol: scm+
      name: grid_meter
      unit_of_measurement: kWh
      icon: mdi:transmission-tower-export
      device_class: energy
    - id: 1552821709
      protocol: scm+
      name: net_meter
      unit_of_measurement: kWh
      icon: mdi:transmission-tower-import
      device_class: energy

